modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="HSR Phainon"
authors="shidran"
description='''Phainon from "Honkai Star Rail"'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/hsr-phainon"
logoFile="icon.png"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    versionRange="[${geckolib_version},)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="playeranimator"
    mandatory=true
    versionRange="[${playerAnimation_version},)"
    ordering="BEFORE"
    side="BOTH"
